version: 2.1

jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.1.2 #teddybnzx/novem_exclusive_gold:latest
        environment:
          PGHOST: 127.0.0.1
      - image: cimg/postgres:10.18
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: novem_exclusive_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle install
          
      # - run:
      #     name: install postgres client
      #     command: |
      #       apt-get update
      #       apt-get install -y postgresql-client

      # - run:
      #     name: Bundler Audit
      #     command: bundle exec bundle audit

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bundle exec rake db:create --trace
