version: 2.1

jobs:
  build:
    parallelism: 1
    docker:
      - image: teddybnzx/novem_exclusive_gold:latest #cimg/ruby:3.2.2-browsers
      - image: cimg/postgres:10.18
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: novem_exclusive_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/app

    steps:
      - checkout
      # - browser-tools/install-browser-tools

      # - node/install:
      #     node-version: 16.13.1
      #     install-yarn: true

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - bundle-v1-{{ checksum "Gemfile.lock" }}
            - bundle-v1-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle install
          
      - run:
          name: install postgres client
          command: |
            apt-get update
            apt-get install -y postgresql-client

      # - run:
      #     name: Bundler Audit
      #     command: bundle exec bundle audit

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bundle exec rake db:create --trace
