development:
  adapter: postgresql
  database: stringer_dev
  encoding: unicode
  pool: 5

test:
  adapter: postgresql
  database: stringer_test
  encoding: unicode
  pool: 5

production:
  url: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  pool: <%= Integer(ENV.fetch("DB_POOL", 15)) %>

novem_exclusive_test:
  adapter: postgresql
  database: novem_exclusive_test
  pool: 5
